language: php
sudo: required
dist: trusty
php:
  - '5.6'
install:
  # Get vendor dependencies (Both PHP and JS)
  - composer install
  - npm install

  # Git Clone OE Dependencies. Sample module contains the MySQL data dump necessary for the unit tests to run.
  - git clone https://github.com/openeyes/eyedraw.git protected/modules/eyedraw
  - git clone https://github.com/openeyes/sample.git protected/modules/sample
before_script:
  - echo 'date.timezone = "Australia/Melbourne"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini # Set the PHP timezone to UTC +10:00:00
  - sudo chmod a+x mysql-ci.sh # Make the shell script to populate the databases executable.
  - ./mysql-ci.sh # Configure the test database
script:
  # Create the runtime folders.
  - mkdir assets
  - mkdir cache
  - cd protected
  - mkdir cache
  - mkdir cache/events

  # Copy the sample config files into place.
  - cp config/local.sample/common.sample.php config/local/common.php
  - cp config/local.sample/console.vagrant.php config/local/console.php

  # Run migrations
  - php yiic migrate --interactive=0
  - php yiic migratemodules --interactive=0
  - php yiic generateuniquecode --interactive=0
  - php yiic generatesessions --interactive=0

  # Run unit tests.
  - cd tests
  - php ../../vendor/phpunit/phpunit/phpunit.php ../modules/OECaseSearch/tests/unit
  - php ../../vendor/phpunit/phpunit/phpunit.php ../modules/OETrial/tests/unit
  - php ../../vendor/phpunit/phpunit/phpunit.php ../modules/OphCiExamination/tests/unit/models/PatientAllergyParameterTest
  - php ../../vendor/phpunit/phpunit/phpunit.php ../modules/OphCiExamination/tests/unit/models/FamilyHistoryParameterTest
  - php ../../vendor/phpunit/phpunit/phpunit.php ./unit/components/DBProviderTest
